/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultsRouteImport } from './routes/vaults'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OraclesOracleIdRouteImport } from './routes/oracles.$oracleId'

const VaultsRoute = VaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OraclesOracleIdRoute = OraclesOracleIdRouteImport.update({
  id: '/oracles/$oracleId',
  path: '/oracles/$oracleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/vaults': typeof VaultsRoute
  '/oracles/$oracleId': typeof OraclesOracleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/vaults': typeof VaultsRoute
  '/oracles/$oracleId': typeof OraclesOracleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/vaults': typeof VaultsRoute
  '/oracles/$oracleId': typeof OraclesOracleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/positions' | '/vaults' | '/oracles/$oracleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/positions' | '/vaults' | '/oracles/$oracleId'
  id: '__root__' | '/' | '/positions' | '/vaults' | '/oracles/$oracleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PositionsRoute: typeof PositionsRoute
  VaultsRoute: typeof VaultsRoute
  OraclesOracleIdRoute: typeof OraclesOracleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracles/$oracleId': {
      id: '/oracles/$oracleId'
      path: '/oracles/$oracleId'
      fullPath: '/oracles/$oracleId'
      preLoaderRoute: typeof OraclesOracleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PositionsRoute: PositionsRoute,
  VaultsRoute: VaultsRoute,
  OraclesOracleIdRoute: OraclesOracleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
