name = "faven-landing"
main = "./src/worker.ts"
compatibility_date = "2026-06-10"

preview_urls = false

[triggers]
crons = ["0 * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "MARKET_DEMAND_CACHE"
id = "67b797203e6f48738cb1f9650aa60797"
