name = "faven-landing"
main = "./src/worker.ts"
compatibility_date = "2026-06-10"

preview_urls = false

[triggers]
crons = ["0 * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "MARKET_DEMAND_CACHE"
id = "REPLACE_WITH_MARKET_DEMAND_CACHE_ID"
preview_id = "REPLACE_WITH_MARKET_DEMAND_CACHE_PREVIEW_ID"
