name = "rfq-server"
main = "src/index.ts"
compatibility_date = "2026-06-10"

#
# = development env
#

[[d1_databases]]
binding = "DB"
database_name = "rfq-server-db-development"
database_id = "local-rfq-server-db"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "QUOTES"
class_name = "QuoteStore"

[[queues.producers]]
binding = "BROADCAST_QUEUE"
queue = "broadcast-server-submissions-development"

[vars]
SUI_RPC_URL = "https://fullnode.testnet.sui.io:443"
OTP_PACKAGE_ID="TBD"

[[queues.consumers]]
queue = "broadcast-server-submissions-development"
max_batch_size = 1
max_batch_timeout = 1
max_concurrency = 1

#
# = production env
#

[[env.production.d1_databases]]
binding = "DB"
database_name = "rfq-server-db"
database_id = "TBD from wrangler d1 create"
migrations_dir = "migrations"

[[env.production.durable_objects.bindings]]
name = "QUOTES"
class_name = "QuoteStore"

[[env.production.queues.producers]]
binding = "BROADCAST_QUEUE"
queue = "broadcast-server-submissions"

[env.production.vars]
SUI_RPC_URL = "https://fullnode.mainnet.sui.io:443"
OTP_PACKAGE_ID="TBD"

[[env.production.queues.consumers]]
queue = "broadcast-server-submissions"
max_batch_size = 1
max_batch_timeout = 1
max_concurrency = 1

#
# = staging env
#

[[env.staging.d1_databases]]
binding = "DB"
database_name = "rfq-server-db-staging"
database_id = "TBD from wrangler d1 create"
migrations_dir = "migrations"

[[env.staging.durable_objects.bindings]]
name = "QUOTES"
class_name = "QuoteStore"

[[env.staging.queues.producers]]
binding = "BROADCAST_QUEUE"
queue = "broadcast-server-submissions-staging"

[env.staging.vars]
SUI_RPC_URL = "https://fullnode.testnet.sui.io:443"
OTP_PACKAGE_ID="TBD"

[[env.staging.queues.consumers]]
queue = "broadcast-server-submissions-staging"
max_batch_size = 1
max_batch_timeout = 1
max_concurrency = 1

[[env.staging.migrations]]
tag = "v1"
new_sqlite_classes = ["QuoteStore"]

#
# = migrations
#

[[migrations]]
tag = "v1"
new_sqlite_classes = ["QuoteStore"]
