name = "broadcast-server"
main = "src/index.ts"
compatibility_date = "2026-06-18"

[[services]]
binding = "RFQ_SERVER"
service = "rfq-server"

[vars]
SUI_RPC_URL = "https://fullnode.mainnet.sui.io:443"

[env.development.vars]
SUI_RPC_URL = "http://127.0.0.1:9000"

[[env.development.services]]
binding = "RFQ_SERVER"
service = "rfq-server"
environment = "development"

[[env.development.queues.consumers]]
queue = "broadcast-server-submissions-development"
max_batch_size = 1
max_batch_timeout = 1

[env.staging.vars]
SUI_RPC_URL = "https://fullnode.testnet.sui.io:443"

[[env.staging.services]]
binding = "RFQ_SERVER"
service = "rfq-server"
environment = "staging"

[[env.staging.queues.consumers]]
queue = "broadcast-server-submissions-staging"
max_batch_size = 1
max_batch_timeout = 1

[[queues.consumers]]
queue = "broadcast-server-submissions"
max_batch_size = 1
max_batch_timeout = 1
